### ISSUE TITLE
ads2bibdesk not working after latest bibdesk update 1st April 2020

### ISSUE THREAD

**Issue by beastfromthedeep** [r-xue/ads2bibdesk#12]
Dear r-xue,

I am a big fan of this code and use it all the time.  However, yesterday I updated bibdesk and it appeared to stop working.  The error message was as follows:

Starting ADS to BibDesk
Traceback (most recent call last):
  File "/Users/hamish/.local/bin/ads2bibdesk", line 10, in <module>
    sys.exit(main())
  File "/Users/hamish/.local/lib/python3.7/site-packages/ads2bibdesk.py", line 90, in main
    article_status=process_article(args ,prefs)
  File "/Users/hamish/.local/lib/python3.7/site-packages/ads2bibdesk.py", line 99, in process_article
    article_status=process_token(args.article_identifier, prefs, bibdesk)
  File "/Users/hamish/.local/lib/python3.7/site-packages/ads2bibdesk.py", line 234, in process_token
    pub = pub.descriptorAtIndex_(1).descriptorAtIndex_(3).stringValue()
AttributeError: 'NoneType' object has no attribute 'descriptorAtIndex_'

Can you please help

EDIT:  I just saw your post about not updating to 1.7.5.  I have gone back to 1.7.4.  Thanks again for all your effort with this program!

**Comment by r-xue** [comment]
Yeah. I saw the same thing and have [reported it ](https://sourceforge.net/p/bibdesk/bugs/1568/)to the BibDesk developer earlier. They will fix it.
