### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'deliverNotification_'

### ISSUE THREAD

**Issue by rhdtownsend** [r-xue/ads2bibdesk#14]
When running ads2bibdesk on the key ADS '1976JAtS...33.2049A', I get the following error:

Starting ADS to BibDesk
Traceback (most recent call last):
  File "/Users/townsend/.local/lib/python3.7/site-packages/ads2bibdesk/ads2bibdesk.py", line 523, in notify
    center.deliverNotification_(notification)
AttributeError: 'NoneType' object has no attribute 'deliverNotification_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/townsend/bin/ads2bibdesk", line 10, in <module>
    sys.exit(main())
  File "/Users/townsend/.local/lib/python3.7/site-packages/ads2bibdesk/ads2bibdesk.py", line 110, in main
    article_status = process_article(args, prefs)
  File "/Users/townsend/.local/lib/python3.7/site-packages/ads2bibdesk/ads2bibdesk.py", line 142, in process_article
    article_status = process_token(args.article_identifier, prefs, bibdesk)
  File "/Users/townsend/.local/lib/python3.7/site-packages/ads2bibdesk/ads2bibdesk.py", line 269, in process_token
    bibdesk('cite key', pid).stringValue(), ads_article.title[0], alert_sound=alert_sound)
  File "/Users/townsend/.local/lib/python3.7/site-packages/ads2bibdesk/ads2bibdesk.py", line 526, in notify
    except ExplicitException:
NameError: name 'ExplicitException' is not defined

Hoping for a quick fix!

**Comment by r-xue** [comment]
I hope the bug is fixed now. 

May I ask which macOS version you're using? 
I changed the default notification delivery method to something likely only works on newer OSs, which exposed the undefined exception type.

**Comment by rhdtownsend** [comment]
This is using Catalina, 10.15.5.

cheers,

Rich

**Comment by rhdtownsend** [comment]
Just re-installed, and it now seems to work OK. Thanks for the quick fix!

**Comment by r-xue** [comment]
No problem! 

Also, I just pushed a change so the code will now have a better chance of getting PDF downloaded correctly. This is for the situation when ADS only links an article's HTML page, like the one you mentioned (1976JAtS...33.2049A).
