### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by distamio** [r-xue/ads2bibdesk#16]
Hi, after updating to Big Sur I can't make it to work. I get the error message below. Any advice appreciated. 
Thanks,
Dimitris
 

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/ads2bibdesk", line 33, in <module>
    sys.exit(load_entry_point('ads2bibdesk==0.2.dev3', 'console_scripts', 'ads2bibdesk')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/ads2bibdesk", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ads2bibdesk/ads2bibdesk.py", line 22, in <module>
    from .bibdesk import BibDesk
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ads2bibdesk/bibdesk.py", line 5, in <module>
    import AppKit  # from pyobjc-framework-Cocoa
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/AppKit/__init__.py", line 10, in <module>
    import Foundation
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/CoreFoundation/__init__.py", line 9, in <module>
    import objc
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/__init__.py", line 6, in <module>
    from . import _objc
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so, 2): Symbol not found: _ffi_find_closure_for_code_np
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_objc.cpython-39-darwin.so

**Comment by r-xue** [comment]
Sorry that I missed your report... Does the issue persist?

It seems that you're using MacPorts and have the packages installed in the site-package area of its Py39 (which I usually avoid). Did you reinstall MacPorts after the Big Sur upgrade?

**Comment by distamio** [comment]
hi, yes the problem seems to have disappeared. Probably some package was updated at some point. thanks
