### ISSUE TITLE
Workflow not working

### ISSUE THREAD

**Issue by agallenne** [r-xue/ads2bibdesk#18]
Thank you for this nice tool. While the command line works in the terminal, this is not the case for the workflow. As it never worked for me (using the new version since about 1 year or more maybe), I thought some may have the same issue so I decided to post the error. When I click to "add to bibdesk", I have the following error:

L’action « Exécuter un script Shell » a rencontré une erreur : « Starting ADS to BibDesk
Traceback (most recent call last):
  File "/Users/agallenn/.local/bin/ads2bibdesk", line 33, in <module>
    sys.exit(load_entry_point('ads2bibdesk==0.2.dev3', 'console_scripts', 'ads2bibdesk')())
  File "/Users/agallenn/.local/lib/python3.8/site-packages/ads2bibdesk/ads2bibdesk.py", line 111, in main
    article_status = process_article(args, prefs)
  File "/Users/agallenn/.local/lib/python3.8/site-packages/ads2bibdesk/ads2bibdesk.py", line 141, in process_article
    bibdesk = BibDesk()
  File "/Users/agallenn/.local/lib/python3.8/site-packages/ads2bibdesk/bibdesk.py", line 19, in __init__
    self.refresh()
  File "/Users/agallenn/.local/lib/python3.8/site-packages/ads2bibdesk/bibdesk.py", line 53, in refresh
    self.titles = self('return title of publications', strlist=True)
  File "/Users/agallenn/.local/lib/python3.8/site-packages/ads2bibdesk/bibdesk.py", line 44, in __call__
    for i in range(output.numberOfItems())]
AttributeError: 'NoneType' object has no attribute 'numberOfItems' »

Note that I always had the same error since I installed your version.

Info system: MacOS 10.15.7, Python 3.8.10, Bibdesk 1.8.3

**Comment by r-xue** [comment]
Hi, It's a known issue (see #8 and #17, also mentioned in [README.rst](https://github.com/r-xue/ads2bibdesk/blob/master/README.rst#installation)). I don't have a quick workaround.
